//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emergy.Data.Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomPropertyValue
    {
        public int Id { get; set; }
        public string SerializedValue { get; set; }
        public Nullable<int> ReportDetails_Id { get; set; }
        public Nullable<int> CustomProperty_Id { get; set; }
    
        public virtual CustomProperty CustomProperty { get; set; }
        public virtual ReportDetail ReportDetail { get; set; }
    }
}
