//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emergy.Data.Visual
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmergyDbVisualModelConnection : DbContext
    {
        public EmergyDbVisualModelConnection()
            : base("name=EmergyDbVisualModelConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<aspnetrole> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetuser> aspnetusers { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customproperty> customproperties { get; set; }
        public virtual DbSet<custompropertyvalue> custompropertyvalues { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<profilephoto> profilephotos { get; set; }
        public virtual DbSet<reportdetail> reportdetails { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<unit> units { get; set; }
    }
}
