
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Emergy.Data.Visual
{

using System;
    using System.Collections.Generic;
    
public partial class location
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public location()
    {

        this.reports = new HashSet<report>();

    }


    public int Id { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public string Name { get; set; }

    public int Type { get; set; }

    public Nullable<int> Unit_Id { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string ApplicationUser_Id { get; set; }



    public virtual unit unit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<report> reports { get; set; }

    public virtual aspnetuser aspnetuser { get; set; }

}

}
