//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emergy.Data.Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Sender_Id { get; set; }
        public string Target_Id { get; set; }
        public string ApplicationUser_Id { get; set; }
        public int Type { get; set; }
        public string ParameterId { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual aspnetuser aspnetuser1 { get; set; }
        public virtual aspnetuser aspnetuser2 { get; set; }
    }
}
