//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emergy.Data.Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Resources = new HashSet<Resource>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string CreatorId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int DetailsId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public System.DateTime DateHappened { get; set; }
        public int Status { get; set; }
        public Nullable<int> Unit_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        public virtual ReportDetail ReportDetail { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
