
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Emergy.Data.Visual
{

using System;
    using System.Collections.Generic;
    
public partial class unit
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public unit()
    {

        this.categories = new HashSet<category>();

        this.customproperties = new HashSet<customproperty>();

        this.locations = new HashSet<location>();

        this.reports = new HashSet<report>();

        this.aspnetusers = new HashSet<aspnetuser>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string AdministratorId { get; set; }

    public System.DateTime DateCreated { get; set; }

    public bool IsPublic { get; set; }



    public virtual aspnetuser aspnetuser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<category> categories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<customproperty> customproperties { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<location> locations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<report> reports { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<aspnetuser> aspnetusers { get; set; }

}

}
