//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emergy.Data.GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalProperty
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TextValue { get; set; }
        public string BoolValue { get; set; }
        public int Type { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> ReportDetails_Id { get; set; }
    
        public virtual ReportDetail ReportDetail { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
