//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emergy.Data.GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public byte[] Base64 { get; set; }
        public Nullable<int> Report_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Report Report { get; set; }
    }
}
